### ISSUE TITLE
Change name?

### ISSUE THREAD

**Issue by igouy** [bluss/ordermap#14]
> original-insertion-order-preserving removal would want to be implemented with tombstones, but I've decided this is going to be a separately named hash map. So: fork time.

Just an idle thought -- OrderMap was a good name for something that does guarantee insertion-order-preserved for all operations, so have a new name for this new thing which does not make that guarantee.

Is there a FastMap ? :-)

**Comment by bluss** [comment]
Maybe. The main feature is that it has a consistent (iteration) order that does not depend on the keys or the hash function.

**Comment by bluss** [comment]
Note that for clarity reasons it did already change name from Order*ed*Map to *OrderMap*

**Comment by igouy** [comment]
What would you call the "separately named hash map" if this one is still called OrderMap ?

**Comment by bluss** [comment]
Renaming seems prudent; the name is the first impression we have, and there we need to deliver the correct expectations about what the map can do.

**NOTE:** This is the name for the datastructure in this crate in its *current* implementation. **current OrderMap** will change name.

The datastructure is a hash table, stored in a compact indexable range, where it keeps insertion order as long as you don't call `.remove()`.

Name Alternatives:

1. LinearMap
2. SequenceMap
3. IndexMap

I prefer **LinearMap** because its succinct, vaguely reminds one of the compactly indexable "Like a Vec" ordering semantics.

Thoughts and wo-hoos are welcome. Please leave well thought out alternative names too. Migration will use deprecation with clear message to point to the new crate name, and there will be a migratory crate version that is 100% API compatible with the other.

**Comment by bluss** [comment]
Thoughts on new name from @nox @cuviper @igouy @Techcable @pczarn @arthurprs @Binero @garro95 and everyone else!?

**Comment by clarcharr** [comment]
`LinearMap` implies linear access time, so, no go for that. I'd personally prefer `OrderedHashMap` or something similar.

**Comment by clarcharr** [comment]
IMO: the name of the type can be succinct but the crate's name should be very precise.

**Comment by bluss** [comment]
I'm not going for that meaning of "linear" here. We can describe a Vec as linear too, and it is constant time indexable; I think it can work.

**Comment by clarcharr** [comment]
@bluss that would be fine, but `linear-map` is already a crate that does linear search. https://crates.io/crates/linear-map

**Comment by bluss** [comment]
Aw, that's too bad.

**Comment by cuviper** [comment]
The reason to rename is so an always-ordered crate can assume the name `OrderMap`?

My next preference is `IndexMap`, since indexing is such a powerful property here.

**Comment by bluss** [comment]
The reason is twofold. Most importantly now that ordermap seems to have delivered the wrong expectations. Secondly, because I think a full insertion order map is important to Rust, to give the name to it.

**Comment by Binero** [comment]
For what it's worth, I think @cuviper's `IndexMap` is a pretty descriptive name.

**Comment by cuviper** [comment]
(it wasn't _my_ name, I just picked it from https://github.com/bluss/ordermap/issues/14#issuecomment-361328366)

**Comment by garro95** [comment]
I like `IndexMap` too

**Comment by arthurprs** [comment]
`IndexMap` sounds reasonable to me 😄

**Comment by Techcable** [comment]
Although I am nostalgic for `OrderMap`, I think it's okay to rename it to either `SequenceMap` or `IndexMap`.

**Comment by bluss** [comment]
I appreciate the feedback!

Now :smile: I'm sorry to capture you like this (it's entirely voluntary), you who have already commented here or those that happen to read this: co-maintainers are also welcome since a good crate needs shared ownership. Maybe we don't have so much to do? The most important goal is just 1.0, and the name should be the only thing left blocking that..

**Comment by cuviper** [comment]
I'm willing to be a co-maintainer.

**Comment by bluss** [comment]
cc @vitiral too, thoughts about the name?

@cuviper Awesome!

Other volunteers are also welcome to help out, of course.

**Comment by vitiral** [comment]
Some other names:
- `IterMap`: to show it's performance when iterating
- `DetMap` with crate name `deterministic_map` to show that iterating is deterministic (very important for tests).
- `IndexMap`: already mentioned, I really like it. I think it gets to the root of what the crate _does_ (... also note... I didn't actually realize indexing was supported in the public API -- cool!).

I think my vote is `IndexMap` but I thought I would spitball the others in case someone else has a _real_ idea.

Also, I will be adding this to the `ergo_std` crate (not yet announced) in the [ergo crate ecosystem](https://github.com/rust-crates/ergo) as I think it should be considered a core type of ergonomic programming. So you chose a good time to rename!

**Comment by bluss** [comment]
DeterministicMap is a good point, DetMap is not a very understandable shortening, but deterministic is right in the realm of names we have been shooting for (even *SteadyMap*).

Note that the current plan is a common release of version 0.4 of ordermap and indexmap that are API-identical (apart from deprecation in ordermap, and the addition of the renamed types in indexmap). Then shortly after that indexmap can be 1.0.

It sounds a bit convoluted but it each step along the plan is simple and actionable. Ideally there should be an indexmap 0.4 that is ready to be rubber stamped as 1.0 soon.

**Comment by vitiral** [comment]
Just so I understand:
- There types currently in `ordermap` are moving to `indexmap` (or some other name) and being renamed accordingly.
- There will be new types in `ordermap` that have some different functionality, i.e. always ordered or something.

Is that right?

**Comment by bluss** [comment]
The second point is a later concern, since no implementation exists, it will of course be a breaking version upgrade.

**Comment by nox** [comment]
I think `DetMap` is pretty good; even if reader is confused at the `Det` part for a few seconds, they'll see `use deterministic_map::DetMap;` somewhere.

**Comment by vitiral** [comment]
`DetMap` has the issue where it is _not_ very deterministic when you do a `remove`, so I'm not sure it is actually the best name.

`IndexMap` kind of has this issue as well -- but then again if you `remove` a value from a `Vec` then the indexes of the other values move around, so that is probably fine. They don't move _randomly_ like they do here, but that's probably okay as well...

**Comment by clarcharr** [comment]
@vitrial this can easily be solved by renaming `remove` to `swap_remove`. It'd be clear what's happening then.

**Comment by Binero** [comment]
@clarcharr `remove` is just a thin wrapper around `swap_remove`. I think if we're going with `IndexMap`, it's important to make `remove` behave like it would on a `Vec`. This would of course be terribly slow, but if performance is an issue, people can always switch over to `swap_remove`.

**Comment by bluss** [comment]
I don't quite follow why `remove()` should change behaviour just because the data structure changes name. Maybe a different name is better then.

`.remove()` is a tricky knot in this case, there is an inconvenient half way solution — no remove method, but an extension trait that adds a `.remove()` method that wraps `.swap_remove()`. That makes dropping in ordermap in as a replacement of the standard `HashMap` one step more complicated.

**Comment by Binero** [comment]
When I think of an `IndexMap` I think of a hybrid between a `Vec` and a `HashMap`. The functions have the same effect to the indices as a `Vec` would have, and the same effect to the keys as a `HashMap` would have. 

In a `HashMap`, the `remove` function removes the key and the value from the collection. In a `Vec` it removes the element and shifts all following elements one position forwards. 

So, in a `IndexMap`, it would be intuitive if a `remove` function would remove the key and value pair, and shift all following elements one position forwards.

**Comment by vitiral** [comment]
@Binero while I agree with you that is slightly more expected, it has _significant_ performance penalties. In most cases the fact that removing an element _can affect the index of other elements_ is enough.

I would go the opposite -- add a `shift_remove` which does what @Binero is suggesting and just make sure docs state the behavior of `remove`.

In the majority of cases I would expect the _performance_ of `remove` to be equivalent to HashMap. The specific behavior is normally not important.

**Comment by Binero** [comment]
In case we want to just focus on the fact the collection works like a `HashMap` which allows for fast iterating, where the indexing features are merely a side-effect of the way it is implemented (and thus not really part of the core-features), I think @vitiral's `IterMap` is more fitting. 

I'm just not sure if we want such a narrow use-case for the collection while it could easily handle more.

**Comment by bluss** [comment]
From discussion in #rust, came the idea that clear docs would be even better than the perfect name.

No name can be so specific that it has the full picture in just the name. I might propose `SteadyMap` instead. With a unique name we can make the meaning clear in docs.

**Comment by arthurprs** [comment]
While I get the motivation, IndexMap still feels way better than SteadyMap.

**Comment by vitiral** [comment]
@Binero 

> In case we want to just focus on the fact the collection works like a HashMap which allows for fast iterating, where the indexing features are merely a side-effect

Something that is fast indexing is pretty much _by definition_ fast at iterating, which is why I think `IndexMap` is probably the better name.

`IterMap` also has the problem that it sounds like the struct you get when you call `IndexMap::iter()` 😆

**Comment by bluss** [comment]
Thanks a lot for being part of the process, `IndexMap` it is! And thanks @cuviper that you want to help out!
